devproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.utils import timezone
from django.views.decorators.cache import cache_page
from django.views.decorators.http import last_modified
from django.views.i18n import JavaScriptCatalog

from misago import __released__, __version__
from misago.plugins.urlpatterns import discover_plugins_urlpatterns
from misago.users.forms.auth import AdminAuthenticationForm


# Cache key for django-i18n.js view that invalidates cache when
# Misago version, release status or language code changes
misago_i18n_cache_key = (
    (f"misagojsi18n_{settings.LANGUAGE_CODE}_{__version__}_{__released__}")
    .replace(".", "_")
    .replace("-", "_")
    .lower()
)


admin.autodiscover()
admin.site.login_form = AdminAuthenticationForm


urlpatterns = discover_plugins_urlpatterns(settings.INSTALLED_PLUGINS) + [
    path("", include("misago.urls", namespace="misago")),
    # Javascript translations
    path(
        "django-i18n.js",
        last_modified(lambda req, **kw: timezone.now())(
            cache_page(86400 * 21, key_prefix=misago_i18n_cache_key)(
                JavaScriptCatalog.as_view(packages=["misago"])
            )
        ),
        name="django-i18n",
    ),
    # Uncomment next line if you plan to use Django admin for 3rd party apps
    path("django-admin/", admin.site.urls),
]


# If debug mode is enabled, include debug toolbar
if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [path("__debug__/", include(debug_toolbar.urls))]


# Use static file server for static and media files (debug only)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# Error Handlers
# Misago needs those handlers to deal with errors raised by it's middlewares
# If you replace those handlers with custom ones, make sure you decorate them
# with shared_403_exception_handler or shared_404_exception_handler
# decorators that are defined in misago.views.errorpages module!
handler403 = "misago.core.errorpages.permission_denied"
handler404 = "misago.core.errorpages.page_not_found"

misago/admin/urls.py
from django.urls import path

from .. import admin
from .views import auth, index, select

urlpatterns = [
    # "misago:admin:index" link symbolises "root" of Misago admin links space
    # any request with path that falls below this one is assumed to be directed
    # at Misago Admin and will be checked by Misago Admin Middleware
    path("", index.admin_index, name="index"),
    path("select/user/", select.select_user, name="select-user"),
    path("logout/", auth.logout, name="logout"),
]

# Discover admin and register patterns
admin.discover_misago_admin()
urlpatterns += admin.urlpatterns()

misago/auth/urls.py
from django.urls import path

from .views import login


urlpatterns = [path("login/", login, name="login")]

misago/urls.py
from django.urls import include, path
from django.views.generic import TemplateView

from . import hooks
from .conf import settings
from .forumindex.views import forum_index
from .parser.views import formatting_help

app_name = "misago"

# Register Misago Apps
urlpatterns = [
    path("", include("misago.analytics.urls")),
    path("", include("misago.auth.urls")),
    path("", include("misago.legal.urls")),
    path("", include("misago.users.urls")),
    path("account/", include("misago.account.urls")),
    path("", include("misago.attachments.urls")),
    path("", include("misago.categories.urls")),
    path("", include("misago.polls.urls")),
    path("", include("misago.posting.urls")),
    path("", include("misago.threads.urls")),
    path("", include("misago.privatethreads.urls")),
    path("", include("misago.threadupdates.urls")),
    path("", include("misago.notifications.urls")),
    path("", include("misago.search.urls")),
    path("", include("misago.oauth2.urls")),
    path("", include("misago.socialauth.urls")),
    path("formatting-help/", formatting_help, name="formatting-help"),
    path("", include("misago.healthcheck.urls")),
    # default robots.txt
    path(
        "robots.txt",
        TemplateView.as_view(
            content_type="text/plain", template_name="misago/robots.txt"
        ),
    ),
    # "misago:index" link symbolises "root" of Misago links space
    # any request with path that falls below this one is assumed to be directed
    # at Misago and will be handled by misago.views.exceptionhandler if it
    # results in Http404 or PermissionDenied exception
    path("", forum_index, name="index"),
]


# Register API
apipatterns = hooks.apipatterns + [
    path("", include("misago.legal.urls.api")),
    path("", include("misago.markup.urls")),
    path("", include("misago.users.urls.api")),
    path("", include("misago.search.urls.api")),
]

urlpatterns += [
    path("api/", include((apipatterns, "api"), namespace="api")),
    path("api/v2/", include("misago.apiv2.urls")),
]


# Register Misago ACP
if settings.MISAGO_ADMIN_PATH:
    # Admin patterns recognised by Misago
    adminpatterns = [path("", include("misago.admin.urls"))]

    admin_prefix = f"{settings.MISAGO_ADMIN_PATH}/"
    urlpatterns += [
        path(admin_prefix, include((adminpatterns, "admin"), namespace="admin"))
    ]

misago/acl/models.py
from django.db import models
from django.utils.translation import pgettext

from .cache import clear_acl_cache


def permissions_default():
    return {}


class BaseRole(models.Model):
    name = models.CharField(max_length=255)
    special_role = models.CharField(max_length=255, null=True, blank=True)
    permissions = models.JSONField(default=permissions_default)

    class Meta:
        abstract = True

    def __str__(self):
        return pgettext("role name", self.name)

    def save(self, *args, **kwargs):
        if self.pk:
            clear_acl_cache()
        return super().save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        clear_acl_cache()
        return super().delete(*args, **kwargs)


class Role(BaseRole):
    pass

misago/attachments/models.py
import os
from functools import cached_property
from hashlib import sha256
from typing import TYPE_CHECKING

from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.crypto import get_random_string

from ..conf import settings
from ..plugins.models import PluginDataModel
from .filetypes import AttachmentFileType, filetypes

if TYPE_CHECKING:
    from ..threads.models import Post


def upload_to(instance: "Attachment", filename: str) -> str:
    salt = sha256(get_random_string(32).encode()).hexdigest()
    filename, extension = instance.filetype.split_name(filename.lower())
    filename_clean = filename[:16] + "." + extension

    return os.path.join("attachments", salt[:2], salt[2:4], salt[-32:], filename_clean)


class Attachment(PluginDataModel):
    category = models.ForeignKey(
        "misago_categories.Category",
        blank=True,
        null=True,
        related_name="+",
        on_delete=models.SET_NULL,
    )
    thread = models.ForeignKey(
        "misago_threads.Thread",
        blank=True,
        null=True,
        related_name="+",
        on_delete=models.SET_NULL,
    )
    post = models.ForeignKey(
        "misago_threads.Post",
        blank=True,
        null=True,
        related_name="+",
        on_delete=models.SET_NULL,
    )

    uploader = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        blank=True,
        null=True,
        related_name="+",
        on_delete=models.SET_NULL,
    )
    uploader_name = models.CharField(max_length=255)
    uploader_slug = models.CharField(max_length=255)

    uploaded_at = models.DateTimeField(default=timezone.now, db_index=True)

    name = models.CharField(max_length=255, db_index=True)
    slug = models.CharField(max_length=255)

    filetype_id = models.CharField(max_length=10, null=True)

    upload = models.FileField(max_length=255, upload_to=upload_to)
    dimensions = models.CharField(max_length=15, null=True)
    size = models.PositiveIntegerField(default=0)

    thumbnail = models.FileField(max_length=255, upload_to=upload_to)
    thumbnail_dimensions = models.CharField(max_length=15, null=True)
    thumbnail_size = models.PositiveIntegerField(default=0)

    is_deleted = models.BooleanField(default=False, db_index=True)

    upload_key: str  # or missing

    class Meta:
        indexes = [
            *PluginDataModel.Meta.indexes,
            models.Index(
                name="misago_attachment_miss_upload",
                fields=["upload"],
                condition=models.Q(upload=""),
            ),
        ]

    def __str__(self):
        return self.name

    def delete(self, *args, **kwargs):
        self.delete_files()
        return super().delete(*args, **kwargs)

    def delete_files(self):
        if self.upload:
            self.upload.delete(save=False)
        if self.thumbnail:
            self.thumbnail.delete(save=False)

    def associate_with_post(self, post: "Post"):
        self.category = post.category
        self.thread = post.thread
        self.post = post

    @cached_property
    def filetype(self) -> AttachmentFileType | None:
        if not self.filetype_id:
            raise ValueError(f"Attachment '{self.name}' is missing 'filetype_id'")

        try:
            return filetypes.get_filetype(self.filetype_id)
        except ValueError:
            return None

    @property
    def filetype_name(self) -> str:
        return str(self.filetype.name)

    @property
    def content_type(self) -> str:
        return self.filetype.content_types[0]

    @property
    def width(self) -> int | None:
        if self.dimensions:
            return int(self.dimensions.split("x")[0])

        return None

    @property
    def height(self) -> int | None:
        if self.dimensions:
            return int(self.dimensions.split("x")[1])

        return None

    @property
    def ratio(self) -> str | None:
        if self.dimensions:
            return (
                ("{:0.2f}".format(self.height * 100 / self.width))
                .rstrip("0")
                .rstrip(".")
            )

        return None

    @property
    def thumbnail_width(self) -> int | None:
        if self.thumbnail_dimensions:
            return int(self.thumbnail_dimensions.split("x")[0])

        return None

    @property
    def thumbnail_height(self) -> int | None:
        if self.thumbnail_dimensions:
            return int(self.thumbnail_dimensions.split("x")[1])

        return None

    def get_absolute_url(self) -> str:
        return reverse(
            "misago:attachment-download", kwargs={"id": self.id, "slug": self.slug}
        )

    def get_thumbnail_url(self) -> str | None:
        if not self.thumbnail:
            return None

        return reverse(
            "misago:attachment-thumbnail",
            kwargs={"id": self.id, "slug": self.slug},
        )

    def get_delete_url(self) -> str:
        return reverse(
            "misago:attachment-delete",
            kwargs={"id": self.id, "slug": self.slug},
        )

    def get_details_url(self) -> str:
        return reverse(
            "misago:attachment-details",
            kwargs={"id": self.id, "slug": self.slug},
        )

misago/cache/models.py
from django.db import models

from .utils import generate_version_string


class CacheVersion(models.Model):
    cache = models.CharField(max_length=128, primary_key=True)
    version = models.CharField(max_length=8, default=generate_version_string)

misago/categories/models.py
from django.db import models
from mptt.managers import TreeManager
from mptt.models import MPTTModel, TreeForeignKey

from ..acl.cache import clear_acl_cache
from ..acl.models import BaseRole
from ..conf import settings
from ..core.utils import slugify
from ..plugins.models import PluginDataModel
from ..threads.threadtypes import trees_map
from .enums import CategoryTree, CategoryChildrenComponent


class CategoryManager(TreeManager):
    def private_threads(self):
        return self.get(level=0, tree_id=CategoryTree.PRIVATE_THREADS)

    def root_category(self):
        return self.get(level=0, tree_id=CategoryTree.THREADS)

    def all_categories(self, include_root=False):
        queryset = self.filter(tree_id=CategoryTree.THREADS)
        if not include_root:
            queryset = queryset.filter(level__gt=0)
        return queryset.order_by("lft")


class Category(MPTTModel, PluginDataModel):
    parent = TreeForeignKey(
        "self", null=True, blank=True, related_name="children", on_delete=models.CASCADE
    )
    special_role = models.CharField(max_length=255, null=True, blank=True)
    name = models.CharField(max_length=255)
    slug = models.CharField(max_length=255)
    short_name = models.CharField(max_length=255, null=True, blank=True)
    color = models.CharField(max_length=7, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    css_class = models.CharField(max_length=255, null=True, blank=True)
    allow_polls = models.BooleanField(default=True)
    delay_browse_check = models.BooleanField(default=False)
    show_started_only = models.BooleanField(default=False)
    is_closed = models.BooleanField(default=False)
    is_vanilla = models.BooleanField(default=False)
    list_children_threads = models.BooleanField(default=True)
    children_categories_component = models.CharField(
        max_length=12,
        null=False,
        blank=False,
        default=CategoryChildrenComponent.FULL,
    )
    threads = models.PositiveIntegerField(default=0)
    posts = models.PositiveIntegerField(default=0)
    unapproved_threads = models.PositiveIntegerField(default=0)
    unapproved_posts = models.PositiveIntegerField(default=0)
    last_posted_at = models.DateTimeField(null=True, blank=True)
    last_thread = models.ForeignKey(
        "misago_threads.Thread",
        related_name="+",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
    )
    last_thread_title = models.CharField(max_length=255, null=True, blank=True)
    last_thread_slug = models.CharField(max_length=255, null=True, blank=True)
    last_poster = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="+",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
    )
    last_poster_name = models.CharField(max_length=255, null=True, blank=True)
    last_poster_slug = models.CharField(max_length=255, null=True, blank=True)
    require_threads_approval = models.BooleanField(default=False)
    require_replies_approval = models.BooleanField(default=False)
    require_edits_approval = models.BooleanField(default=False)
    prune_started_after = models.PositiveIntegerField(default=0)
    prune_replied_after = models.PositiveIntegerField(default=0)
    archive_pruned_in = models.ForeignKey(
        "self",
        related_name="pruned_archive",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
    )

    objects = CategoryManager()

    class Meta:
        indexes = PluginDataModel.Meta.indexes

    def __str__(self):
        return str(self.thread_type.get_category_name(self))

    @property
    def thread_type(self):
        return trees_map.get_type_for_tree_id(self.tree_id)

    def delete(self, *args, **kwargs):
        clear_acl_cache()
        return super().delete(*args, **kwargs)

    def synchronize(self):
        threads_queryset = self.thread_set.filter(is_hidden=False, is_unapproved=False)
        self.threads = threads_queryset.count()

        if self.threads:
            replies_sum = threads_queryset.aggregate(models.Sum("replies"))
            self.posts = self.threads + replies_sum["replies__sum"]
        else:
            self.posts = 0

        if self.threads:
            last_thread_qs = threads_queryset.filter(
                is_hidden=False, is_unapproved=False
            )
            last_thread = last_thread_qs.order_by("-last_posted_at")[:1][0]
            self.set_last_thread(last_thread)
        else:
            self.empty_last_thread()

    def get_absolute_url(self):
        return self.thread_type.get_category_absolute_url(self)

    def get_last_thread_url(self):
        return self.thread_type.get_category_last_thread_url(self)

    def get_last_thread_new_url(self):
        return self.thread_type.get_category_last_thread_new_url(self)

    def get_last_post_url(self):
        return self.thread_type.get_category_last_post_url(self)

    def set_name(self, name):
        self.name = name
        self.slug = slugify(name)

    def set_last_thread(self, thread):
        self.last_posted_at = thread.last_posted_at
        self.last_thread = thread
        self.last_thread_title = thread.title
        self.last_thread_slug = thread.slug
        self.last_poster = thread.last_poster
        self.last_poster_name = thread.last_poster_name
        self.last_poster_slug = thread.last_poster_slug

    def empty_last_thread(self):
        self.last_posted_at = None
        self.last_thread = None
        self.last_thread_title = None
        self.last_thread_slug = None
        self.last_poster = None
        self.last_poster_name = None
        self.last_poster_slug = None

    def has_child(self, child):
        return child.lft > self.lft and child.rght < self.rght


class CategoryRole(BaseRole):
    pass


class RoleCategoryACL(models.Model):
    role = models.ForeignKey(
        "misago_acl.Role", related_name="categories_acls", on_delete=models.CASCADE
    )
    category = models.ForeignKey(
        "Category", related_name="category_role_set", on_delete=models.CASCADE
    )
    category_role = models.ForeignKey(CategoryRole, on_delete=models.CASCADE)

misago/admin/templates/misago/admin/base.html
{% load i18n static %}
<!doctype html>
<html lang="{{ LANGUAGE_CODE }}">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% spaceless %}{% block title %}{% translate "Misago Administration" context "admin title" %}{% endblock %}{% endspaceless %}</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <link href="{% static 'misago/admin/index.css' %}" rel="stylesheet">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'misago/admin/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'misago/admin/favicon-32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'misago/admin/favicon-16.png' %}">
    <link rel="shortcut icon" href="{% static 'misago/admin/favicon.ico' %}">
    {% block extra-head %}{% endblock extra-head %}
  </head>
  {% block body %}{% endblock %}
</html>

misago/admin/templates/misago/admin/icons.html
{% extends "misago/admin/conf/form.html" %}
{% load i18n misago_admin_form %}


{% block form-body %}
<div class="form-fieldset">
  <fieldset>
    <legend>{% translate "Favicon" context "admin icons form" %}</legend>

    <p>
      {% translate "Favicon is small icon that internet browsers display next to your site in its interface." context "admin icons form" %}
    </p>

    {% if icons.favicon or icons.favicon_16 or icons.favicon_32 %}
      <div class="row justify-content-left align-items-end mt-1 mb-3">
        {% if icons.favicon %}
          <div class="col-auto">
            <div class="control-image-preview control-image-metadata">
              <div class="p-0 m-0 d-flex align-items-center justify-content-center" style="height: 48px; width: 128px;">
                <img src="{{ icons.favicon.image.url }}" alt="" />
              </div>
              <div>
                <span>{{ icons.favicon.size|filesizeformat }}</span>
                <span>{{ icons.favicon.width }}&times;{{ icons.favicon.height }}</span>
              </div>
            </div>
          </div>
        {% endif %}
        {% if icons.favicon_32 %}
          <div class="col-auto">
            <div class="control-image-preview control-image-metadata">
              <div class="p-0 m-0 d-flex align-items-center justify-content-center" style="height: 48px; width: 128px;">
                <img src="{{ icons.favicon_32.image.url }}" alt="" />
              </div>
              <div>
                <span>{{ icons.favicon_32.size|filesizeformat }}</span>
                <span>{{ icons.favicon_32.width }}&times;{{ icons.favicon_32.height }}</span>
              </div>
            </div>
          </div>
        {% endif %}
        {% if icons.favicon_16 %}
          <div class="col-auto">
            <div class="control-image-preview control-image-metadata">
              <div class="p-0 m-0 d-flex align-items-center justify-content-center" style="height: 48px; width: 128px;">
                <img src="{{ icons.favicon_16.image.url }}" alt="" />
              </div>
              <div>
                <span>{{ icons.favicon_16.size|filesizeformat }}</span>
                <span>{{ icons.favicon_16.width }}&times;{{ icons.favicon_16.height }}</span>
              </div>
            </div>
          </div>
        {% endif %}
      </div>
    {% endif %}
  
    {% form_row form.favicon %}

    {% if icons.favicon or icons.favicon_16 or icons.favicon_32 %}
      {% form_checkbox_row form.favicon_delete %}
    {% endif %}

  </fieldset>
</div>
<div class="form-fieldset">
  <fieldset>
    <legend>{% translate "Apple Touch Icon" context "admin icons form" %}</legend>

    <p>
      {% translate "Apple devices and Safari web browser will use this image to represent the site in its interfaces." context "admin icons form" %}
    </p>

    {% if icons.apple_touch_icon %}
      <div class="control-image-preview control-image-metadata mt-1 mb-3">
        <img src="{{ icons.apple_touch_icon.image.url }}" alt="" />
        <div>
          <span>{{ icons.apple_touch_icon.size|filesizeformat }}</span>
          <span>
            {{ icons.apple_touch_icon.width }}&times;{{ icons.apple_touch_icon.height }}
          </span>
        </div>
      </div>
    {% endif %}

    {% form_row form.apple_touch_icon %}
    {% if icons.apple_touch_icon %}
      {% form_checkbox_row form.apple_touch_icon_delete %}
    {% endif %}

  </fieldset>
</div>
{% endblock form-body %}

misago/admin/templates/misago/admin/layout.html
{% extends "misago/admin/base.html" %}
{% load static %}


{% block body %}
<body>
  {% include "misago/admin/navbar.html" %}

  <div class="container-fluid my-3 pb-3">
    <div class="row">
      <div class="col col-nav-side">
        {% include "misago/admin/sidenav.html" %}
      </div>
      <div class="col">
        {% include "misago/admin/messages.html" %}
        {% block content %}{% endblock %}
      </div>
    </div>
  </div>

  {# We include JavaScript at the end of page body so it renders faster #}
  <script type="text/javascript" src="{% static 'misago/admin/index.js' %}"></script>
  {% if ADMIN_MOMENTJS_LOCALE_URL %}
    <script type="text/javascript" src="{% static ADMIN_MOMENTJS_LOCALE_URL %}"></script>
  {% endif %}
  <script type="text/javascript">
    window.misago.init()
  </script>
  {% block javascript %}{% endblock javascript %}
</body>
{% endblock body %}

misago/admin/templates/misago/admin/login.html
{% extends "misago/admin/base.html" %}
{% load i18n static %}


{% block title %}
  {% translate "Log in" context "admin login form" %} | {% if target == "django" %}{% translate "Django Administration" context "admin title" %}{% else %}{% translate "Misago Administration" context "admin title" %}{% endif %}
{% endblock %}


{% block body %}
<body class="login-form">
  <form class="login-form-container" method="post" role="form">
    {% csrf_token %}
    <div class="login-form-logo">
      {% if target == "misago" %}
        <img src="{% static 'misago/admin/img/misago.png' %}" alt="Misago">
      {% elif target == "django" %}
        <img src="{% static 'misago/admin/img/django.png' %}" alt="Django">
      {% endif  %}
    </div>

    <div class="card login-form-card">
      <div class="card-body">
        <h1 class="card-title login-form-title">{% translate "Administration" context "admin login form" %}</h1>

        {% for error in form.non_field_errors %}
          <p class="alert alert-danger text-center" role="alert">
            {{ error }}
            <br>{% translate "Please try again." context "admin login form" %}
          </p>
        {% endfor %}
        {% for message in messages %}
          {% if 'success' in message.tags %}
            <div class="alert alert-success text-center" role="alert">
          {% elif 'warning' in message.tags %}
            <div class="alert alert-warning text-center" role="alert">
          {% elif 'error' in message.tags %}
            <div class="alert alert-danger text-center" role="alert">
          {% else %}
            <div class="alert alert-info text-center" role="alert">
          {% endif %}
              {{ message }}
            </div>
        {% endfor %}

        <div class="form-group">
          <div class="control-input">
            <input
              type="text"
              name="username"
              class="form-control input-lg"
              placeholder="{% translate 'Username or email' context 'admin login form' %}"
              value="{{ form.username.value|default:'' }}"
            >
          </div>
        </div>
        <div class="form-group">
          <div class="control-input">
            <input
              type="password"
              name="password"
              class="form-control input-lg"
              placeholder="{% translate 'Password' context 'admin login form' %}"
            >
          </div>
        </div>
        <button class="btn btn-primary btn-block">
          {% translate "Sign in" context "admin login form btn" %}
        </button>
        <a href="{% url 'misago:index' %}" class="btn btn-light btn-block">
          {% translate "Return to site" context "admin login form btn" %}
        </a>
      </div>
    </div>
  </form>
</body>
{% endblock body %}

misago/admin/templates/misago/admin/messages.html
{% load i18n %}
{% for message in messages %}
  {% if 'info' in message.tags %}
    <p class="alert alert-info">
  {% elif 'success' in message.tags %}
    <p class="alert alert-success">
  {% elif 'warning' in message.tags %}
    <p class="alert alert-warning">
  {% elif 'error' in message.tags %}
    <p class="alert alert-danger">
  {% endif %}
    {{ message }}
  </p>
{% endfor %}

misago/admin/templates/misago/admin/navbar.html
{% load i18n static misago_avatars %}
<nav class="navbar navbar-expand-lg navbar-light bg-white shadow-sm">
  <a class="navbar-brand" href="{% url 'misago:admin:index' %}">
    <img src="{% static 'misago/admin/img/mred.png' %}" alt="">
    <span>Misago</span>
  </a>
  <span class="badge badge-light mr-auto">
    {{ MISAGO_VERSION }}
  </span>
  <a href="https://github.com/rafalp/misago" target="_blank" class="btn btn-light btn-sm mr-3">
    <span class="fab fa-github"></span>
    {% translate "GitHub" context "admin navbar" %}
  </a>
  <a href="https://misago-project.org" target="_blank" class="btn btn-light btn-sm mr-3">
    <span class="far fa-question-circle"></span>
    {% translate "Support forum" context "admin navbar" %}
  </a>
  <a href="{% url 'misago:index' %}" class="btn btn-light btn-sm mr-3">
    <span class="far fa-window-maximize"></span>
    {% translate "Site index" context "admin navbar" %}
  </a>
  <div class="dropdown">
    <button type="button" class="btn btn-user dropdown-toggle" id="openAdminDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <img src="{{ user|avatar:30 }}" alt="{% translate 'Your avatar' context 'admin navbar' %}">
    </button>
    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="openAdminDropdown">
      <h6 class="dropdown-header">{{ user }}</h6>
      <a class="dropdown-item" href="{% url 'misago:admin:users:edit' pk=user.pk %}">
        {% translate "Edit your account" context "admin navbar" %}
      </a>
      <div class="dropdown-divider"></div>
      <form action="{% url 'misago:admin:logout' %}" method="post">
        {% csrf_token %}
        <button type="submit" class="dropdown-item">
          {% translate "Close admin session" context "admin navbar" %}
        </button>
      </form>
      <form action="{% url 'misago:logout' %}" method="post">
        {% csrf_token %}
        <button type="submit" class="dropdown-item">
          {% translate "Log out completely" context "admin navbar" %}
        </button>
      </form>
    </div>
  </div>
</nav>

misago/admin/templates/misago/admin/permissions_table.html
{% load i18n misago_admin_form %}
<div class="form-fieldset">
  <fieldset>
    <legend>{{ form.legend }}</legend>
    {% for field in form %}
      {% form_row field %}
    {% endfor %}
  </fieldset>
</div>

misago/admin/templates/misago/admin/sidenav.html
{% load i18n %}
<nav class="nav nav-side">
  {% for node in sections %}
    <a class="nav-link nav-section{% if node.is_active %} active{% endif %}" href="{{ node.link }}">
      <div class="media-icon">
        <span class="{{ node.icon }}"></span>
      </div>
      <div class="media-body">
        {{ node.name }}
      </div>
    </a>
    {% if node.is_active and actions %}
      {% for subnode in actions %}
        <a class="nav-link nav-action{% if subnode.is_active %} active{% endif %}" href="{{ subnode.link }}">
          <div class="media-body">
            {{ subnode.name }}
          </div>
        </a>
      {% endfor %}
    {% endif %}
  {% endfor %}
</nav>